# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-11 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaestudiante',
            name='disponibilidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.DisponibilidadHoraria'),
        ),
    ]
