# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-11 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_reservaestudiante_disponibilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadhoraria',
            name='tiempo_minutos',
            field=models.DurationField(default=30),
        ),
    ]
