# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-11 23:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190811_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadhoraria',
            name='tiempo_minutos',
            field=models.DurationField(default=datetime.timedelta(0, 1800)),
        ),
    ]
